export const BLOG_POSTS_FETCH_REQUEST = 'BLOG_POSTS_FETCH_REQUEST';
export const BLOG_POSTS_FETCH_SUCCESS = 'BLOG_POSTS_FETCH_SUCCESS';
export const BLOG_POSTS_FETCH_FAILURE = 'BLOG_POSTS_FETCH_FAILURE';
export const BLOG_USER_SELECTED = 'BLOG_USER_SELECTED';
export const BLOG_USER_CLOSE = 'BLOG_USER_CLOSE';
