export const BOOKS_ITEM_SELECTED = 'BOOKS_ITEM_SELECTED';
export const BOOKS_VIEW_CHANGED = 'BOOKS_VIEW_CHANGED';
export const BOOKS_SEARCH_REQUEST = 'BOOKS_SEARCH_REQUEST';
export const BOOKS_ITEM_CLOSE = 'BOOKS_ITEM_CLOSE';
