// blog section
export const BLOG_POSTS_FETCH_REQUEST = 'BLOG_POSTS_FETCH_REQUEST';
export const BLOG_POSTS_FETCH_SUCCESS = 'BLOG_POSTS_FETCH_SUCCESS';
export const BLOG_POSTS_FETCH_FAILURE = 'BLOG_POSTS_FETCH_FAILURE';
export const BLOG_USER_SELECTED = 'BLOG_USER_SELECTED';
export const BLOG_USER_CLOSE = 'BLOG_USER_CLOSE';

// podcast section
export const PODCASTS_ITEM_SELECTED = 'PODCASTS_ITEM_SELECTED';

// book section
export const BOOKS_ITEM_SELECTED = 'BOOKS_ITEM_SELECTED';
export const BOOKS_VIEW_CHANGED = 'BOOKS_VIEW_CHANGED';
export const BOOKS_SEARCH_REQUEST = 'BOOKS_SEARCH_REQUEST';
export const BOOKS_ITEM_CLOSE = 'BOOKS_ITEM_CLOSE';

// modal
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
