export const GOOGLEMAP_MOUNT_STATUS_NONE = 'GOOGLEMAP_MOUNT_STATUS_NONE';
export const GOOGLEMAP_MOUNT_STATUS_LOADING = 'GOOGLEMAP_MOUNT_STATUS_LOADING';
export const GOOGLEMAP_MOUNT_STATUS_READY = 'GOOGLEMAP_MOUNT_STATUS_READY';
export const GOOGLEMAP_MOUNT_STATUS_ERROR = 'GOOGLEMAP_MOUNT_STATUS_ERROR';
